### ISSUE TITLE
CLI utility to peek/poke at registers

### ISSUE THREAD

**Issue by nebulous** [dulitz/finitude#2]
I've been meaning to write this for letsee.. I guess at least 7 years (https://github.com/nebulous/infinitude/commit/9305c1aa8295d369f8c530080eca8b4de84745e5) and if I still haven't gotten around to it, maybe it's time to prod someone else 😄 

What I'd love to have is a command line utility which allows for prodding/reading back registers. Just a little single-use thing without a lot of flags, or features, or fanciness. The utility would only read/make frames and toss them onto the wire/telnet.

eg
`./carprod read 0x003b03 > payload`

...tinker with payload in a hex editor or whatever, then

`cat payload | ./carprod write 0x03b03 -`

That way we could have a standard way to request example data from others, implement scanners, pipe thru netcat/socat, or experiment with quick pokes at a certain register to test. Maybe Golang makes the most sense for a utility like this, but @acd hasn't been active in a while and you have, plus everyone who cares about this stuff probably has python3 anyway.

Does that make sense to you and do you want to do it?

**Comment by dulitz** [comment]
Yeah I have this. Let me get another release out (possibly today) -- I did a major code reorg an need to test things again first.

**Comment by dulitz** [comment]
Well my release is not happening today. :) But reading over the issue in more detail, I'm not sure I really have what you asked for. I have questions.

What I have is a module that will send a READ frame for a register of your choosing and parse the response into fields, to the best of our knowledge of that register's structure. That covers several of your use cases. Example output:

```
to 0x4001 from 0x2001 len 3 READ(0xb) LastStatus(031c)
to 0x2001 from 0x4001 len 43 ACK06(0x6) LastStatus(031c) StatusCode:33, Severity:3, Message:'LIMIT FAULT'
to 0x4001 from 0x2001 len 3 READ(0xb) Temperatures(0302)
to 0x2001 from 0x4001 len 15 ACK06(0x6) Temperatures(0302) TempSensors:[{'State': 4, 'Type': 17, 'TempTimes16': 0}, {'State': 4, 'Type': 20, 'TempTimes16': 0}, {'State': 4, 'Type': 2, 'TempTimes16': 0}]
```

That module also allows you to send a WRITE frame. But the format of the WRITE frame's data field is just a byte string, not parsed fields. So it's not so easy to experiment with quick pokes.

Then again, why do you want to do quick pokes?

It seems to me that people working on this have had various goals over time.

1. "Emulate a SAM, for people who don't have a SAM." That means that you only need to communicate with the thermostat, and you only read and write the registers that the SAM reads and writes.
2. Go beyond (1) and allow remote observation of things the thermostat displays, even if the SAM doesn't know about them.
3. Go beyond (2) and allow remote observation of things that are communicated on the bus but that the thermostat doesn't display, say to check on the health of your system.
4. Go beyond (1) and allow remote control of things the thermostat controls, even if the SAM doesn't know about them.
5. Emulate a smart sensor, so you can use your PurpleAir or Ambient Weather to report temperature and/or humidity for a zone.
6. Emulate a zone damper control module, so you can use non-Carrier/Bryant zone dampers (e.g. a Zigbee or Z-Wave damper).
7. Emulate a thermostat, for people who don't have a thermostat.

Which of those do you want to do quick pokes for? And is the parsed output of the read in a format that is understandable, do you think?

**Comment by nebulous** [comment]
What I'm looking for is a CLI utility which would follow the UNIX philosophy of doing one thing and doing it well - allowing for other tools to build upon it in pipes(that's why Golang seemed to be a good fit since Go makes it easy to just release a binary). 

So, while at one point or another I've been interested in 1 thru 7, and said utility _could_ be used for any of the above, it would really be more of a research tool/standard way to bundle and unbundle binary frames. It's also entirely possible that I'm the only person who wants to interact with the bus in this manner and I should stop being so lazy and just implement it in perl or C (rather than stubbornly thinking to myself "self, this would be a good excuse to learn Go or Rust") 😄  

Tangent: my setup is a bit weird anyway as I have an esp8266 hooked directly up to the bus which actually syncs/parses frames on the microcontroller before making them available over tcp/telnet, so I should probably just implement the reverse: adding the header and checksum as well, then throw that source into infinitude `contrib/` along with cardump.

**Comment by dulitz** [comment]
I'd be willing to package such a utility but I really don't understand what it's for, why I would pipe. I want the tools to support workflows that will be useful, and to disincentivize workflows that won't. Right now I'm only seeing workflows that won't be useful in discovery or in production, so maybe you can help me. :)

* For production use (whether emulating a SAM, smart sensor, or zone damper control), we want a server, not command line tools. The main reason this is so is that if you observe bus traffic for 60 seconds you know basically everything about system state without having to lift a finger. Any single READ or WRITE transaction is unreliable, that's why the Bryant/Carrier modules constantly repeat themselves -- eventually the correct value will get through. That's a server function.
* For determining how to emulate a SAM, smart sensor, or zone damper control it's sufficient to observe bus frames as the module operates. It's not necessary or helpful to send READ frames.
* For showing non-SAM info the thermostat displays or uses it's also sufficient to observe bus frames, because the thermostat sends READ frames to obtain all the data it shows or uses. It's not helpful to send our own. The thermostat sends its READ frames every few seconds and the response comes back.

Reading the RegisterInfo register, which tells us what registers exist on a module and which ones are writable, is an example of a thing that doesn't happen in ordinary system operation but can be (marginally) useful for us. RegisterInfo isn't writable though so it's not a use case for piping.

There is so much unknown about the above, and the path to learning more is so clear, I honestly think everyone with an interest in the ABCD bus should be working on those things. If we don't know what 75% of the data being passed around the bus in normal operation means, why would we expect to learn anything interesting by poking at registers unused in normal operation? I mean, we _could_, it's not impossible, but down one path is the obvious tasty fruit of learning and what's down the other path is unclear.

So I think there's something I'm missing about your desired use case and will need help if I'm to satisfy it I think.

**Comment by nebulous** [comment]
That’s fine, I’ve burned too much of your time in this thread anyway to scratch an itch that others don’t have.

**Comment by dulitz** [comment]
I don't feel I wasted my time. I got to articulate a positive view of what I felt was useful. I look forward to learning what you're gonna do. :)
